version: "3.9"

services:
  backend:
    build: ./backend
    container_name: lms_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: python -m uvicorn backend.asgi:application --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    container_name: lms_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    command: npm run dev

